name: senior
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch=1.4.0
  - cudatoolkit=10.1
  - absl-py
  - pyparsing
  - pip
  - pip:
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+git://github.com/facebookresearch/hydra@0.11_branch
    - matplotlib
    - glfw==1.11.2
    - scikit-image
    - scikit-learn
    - cython==0.29.21
    - 'mujoco-py<2.2,>=2.1'
