# hanle press
python train_SENIOR.py env=metaworld_handle-press-v2 max_feedback=250 reward_batch=10 curiosity_fre=1000 num_interact=5000 num_meta_steps=10000 agent.params.batch_size=512 seed=12345 time_decrease=0.01 agent.params.actor_lr=3e-4 agent.params.critic_lr=3e-4 double_q_critic.params.hidden_depth=3 double_q_critic.params.hidden_dim=256 diag_gaussian_actor.params.hidden_depth=3 diag_gaussian_actor.params.hidden_dim=256
# window open
python train_SENIOR.py env=metaworld_window-open-v2 max_feedback=250 reward_batch=10 curiosity_fre=500 num_interact=5000 num_meta_steps=10000 agent.params.batch_size=512 seed=12345 time_decrease=0.01 agent.params.actor_lr=3e-4 agent.params.critic_lr=3e-4 double_q_critic.params.hidden_depth=3 double_q_critic.params.hidden_dim=256 diag_gaussian_actor.params.hidden_depth=3 diag_gaussian_actor.params.hidden_dim=256
# door lock
python train_SENIOR.py env=metaworld_door-lock-v2 max_feedback=250 reward_batch=5 curiosity_fre=1000 num_interact=5000 num_meta_steps=10000 agent.params.batch_size=512 seed=12345 time_decrease=0.01 agent.params.actor_lr=3e-4 agent.params.critic_lr=3e-4 double_q_critic.params.hidden_depth=3 double_q_critic.params.hidden_dim=256 diag_gaussian_actor.params.hidden_depth=3 diag_gaussian_actor.params.hidden_dim=256
# window close
python train_SENIOR.py env=metaworld_window-close-v2 max_feedback=250 reward_batch=5 curiosity_fre=500 num_interact=5000 num_meta_steps=10000 agent.params.batch_size=512 seed=12345 time_decrease=0.01 agent.params.actor_lr=3e-4 agent.params.critic_lr=3e-4 double_q_critic.params.hidden_depth=3 double_q_critic.params.hidden_dim=256 diag_gaussian_actor.params.hidden_depth=3 diag_gaussian_actor.params.hidden_dim=256
# door unlock
python train_SENIOR.py env=metaworld_door-unlock-v2 max_feedback=1000 reward_batch=20  curiosity_fre=500 num_interact=5000 num_meta_steps=10000 agent.params.batch_size=512 seed=12345 time_decrease=0.01 agent.params.actor_lr=3e-4 agent.params.critic_lr=3e-4 double_q_critic.params.hidden_depth=3 double_q_critic.params.hidden_dim=256 diag_gaussian_actor.params.hidden_depth=3 diag_gaussian_actor.params.hidden_dim=256
# door open
python train_SENIOR.py env=metaworld_door-open-v2 max_feedback=1000 reward_batch=10 curiosity_fre=1000 num_interact=5000 num_meta_steps=10000 agent.params.batch_size=512 seed=12345 time_decrease=0.01 agent.params.actor_lr=3e-4 agent.params.critic_lr=3e-4 double_q_critic.params.hidden_depth=3 double_q_critic.params.hidden_dim=256 diag_gaussian_actor.params.hidden_depth=3 diag_gaussian_actor.params.hidden_dim=256